# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJTzX6N1PTRAoo-JVO5YwUPsfNBtKELH
"""

from flask import Flask, request, jsonify
import pickle
import numpy as np

app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))

@app.route('/')
def home():
    return "Student Performance Prediction API Running!"

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json
    input_data = np.array(list(data.values())).reshape(1, -1)
    prediction = model.predict(input_data)

    return jsonify({
        "predicted_score": float(prediction[0])
    })

if __name__ == "__main__":
    app.run(debug=True)