# -*- coding: utf-8 -*-
"""Task-3 Codetech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTTxjPwi4DkmlNH6eB_Jz7lr5iq1kXrq
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/exams.csv')

df = pd.read_csv('/content/exams.csv')
df.head(10)

df.info()
df.describe()

df = pd.get_dummies(df, drop_first=True)
df.head()

X = df.drop('math score', axis=1)   # Target column
y = df['math score']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions[:5]

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MSE:", mse)
print("R2 Score:", r2)

import pickle

pickle.dump(model, open('model.pkl', 'wb'))
print("Model saved successfully!")

from google.colab import files

files.download('model.pkl')